version: "3"
services:
    mysql:
        image: mysql:latest
        user: ${CURRENT_UID}   # run by current user, should run CURRENT_UID=$(id -u):$(id -g) before docker-compose up
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root  # change to your password!
        command: --default-authentication-plugin=mysql_native_password

    redis:
        image: redis:latest
        volumes:
            - ./data/redis:/data
            - ./conf/redis/redis.conf:/etc/redis/redis.conf
        networks:
            - mysql
        ports:
            - "6379:6379"
        sysctls:
            - net.core.somaxconn=1024
        command: >
            bash -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf
            && redis-server /etc/redis/redis.conf --appendonly yes"
    php-fpm73:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.php73
        volumes:
            - ../project:/var/www/html
            - ./conf/php:/usr/local/etc/php
            - ./conf/supervisor:/etc/supervisor/conf.d
        networks:
            - mysql
            - nginx
        ports:
            - "9000:9000"

    nginx:
        image: nginx:alpine
        volumes:
            - ../project:/var/www/html
            - ./conf/nginx:/etc/nginx
            - ./log/nginx:/var/log/nignx
            - ./ssl:/etc/nginx/ssl
        networks:
            - nginx
        ports:
            - "80:80"
            - "443:443"

networks:
    mysql:
    nginx:
